version: '3'

services:
  # web:
  #   container_name: jwnet_web
  #   image: httpd:latest
  #   networks:
  #     default: null
  #   ports:
  #     - mode: ingress
  #       target: 80
  #       published: 5000
  #       protocol: tcp
  #   #restart: always
  #   volumes:
  #     - type: bind
  #       source: ./html
  #       target: /usr/local/apache2/htdocs
  #       #bind:
  #         #create_host_path: true
  app:
    image: node:16
    tty: true
    volumes:
      - ./html:/src
    working_dir: "/src/"
    ports:
      - "5173:5173"

  # php:
  #   build: ./php
  #   volumes:
  #     - ./html/dist:/usr/share/nginx/html
  #     - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  web:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/dist:/usr/share/nginx/html
    #restart: always
    ports: ["5000:80"]
    # depends_on: ["php"]

# networks:
#   default:
#     name: jwnet_default
